package voice.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val LightColorScheme = lightColorScheme(
  primary = VoiceColors.Light.PrimaryBlue.shade50,
  onPrimary = VoiceColors.Light.NeutralGray.white,
  primaryContainer = VoiceColors.Light.PrimaryBlue.shade10,
  onPrimaryContainer = VoiceColors.Light.PrimaryBlue.shade90,
  secondary = VoiceColors.Light.AccentOrange.shade50,
  onSecondary = VoiceColors.Light.NeutralGray.white,
  secondaryContainer = VoiceColors.Light.AccentOrange.shade10,
  onSecondaryContainer = VoiceColors.Light.AccentOrange.shade90,
  tertiary = VoiceColors.Light.PrimaryBlue.shade40,
  onTertiary = VoiceColors.Light.NeutralGray.white,
  tertiaryContainer = VoiceColors.Light.PrimaryBlue.shade20,
  onTertiaryContainer = VoiceColors.Light.PrimaryBlue.shade80,
  error = VoiceColors.Light.AccentOrange.shade70,
  onError = VoiceColors.Light.NeutralGray.white,
  errorContainer = VoiceColors.Light.AccentOrange.shade20,
  onErrorContainer = VoiceColors.Light.AccentOrange.shade100,
  background = VoiceColors.Light.NeutralGray.white,
  onBackground = VoiceColors.Light.NeutralGray.shade100,
  surface = VoiceColors.Light.NeutralGray.white,
  onSurface = VoiceColors.Light.NeutralGray.shade100,
  surfaceVariant = VoiceColors.Light.NeutralGray.shade5,
  onSurfaceVariant = VoiceColors.Light.NeutralGray.shade60,
  outline = VoiceColors.Light.NeutralGray.shade40,
  outlineVariant = VoiceColors.Light.NeutralGray.shade20,
  scrim = VoiceColors.Light.NeutralGray.black,
  inverseSurface = VoiceColors.Light.NeutralGray.shade90,
  inverseOnSurface = VoiceColors.Light.NeutralGray.shade10,
  inversePrimary = VoiceColors.Light.PrimaryBlue.shade30,
  surfaceTint = VoiceColors.Light.PrimaryBlue.shade50,
)

val DarkColorScheme = darkColorScheme(
  primary = VoiceColors.Dark.PrimaryBlueBright.shade60,
  onPrimary = VoiceColors.Dark.Text.primary,
  primaryContainer = VoiceColors.Dark.PrimaryBlueBright.shade30,
  onPrimaryContainer = VoiceColors.Dark.Text.primary,
  secondary = VoiceColors.Dark.AccentOrangeBright.shade50,
  onSecondary = VoiceColors.Dark.Text.primary,
  secondaryContainer = VoiceColors.Dark.AccentOrangeBright.shade60,
  onSecondaryContainer = VoiceColors.Dark.Text.primary,
  tertiary = VoiceColors.Dark.PrimaryBlueBright.shade70,
  onTertiary = VoiceColors.Dark.Text.primary,
  tertiaryContainer = VoiceColors.Dark.PrimaryBlueBright.shade40,
  onTertiaryContainer = VoiceColors.Dark.Text.primary,
  error = VoiceColors.Dark.AccentOrangeBright.shade60,
  onError = VoiceColors.Dark.Text.primary,
  errorContainer = VoiceColors.Dark.AccentOrangeBright.shade40,
  onErrorContainer = VoiceColors.Dark.Text.primary,
  background = VoiceColors.Dark.Surface.main,
  onBackground = VoiceColors.Dark.Text.primary,
  surface = VoiceColors.Dark.Surface.main,
  onSurface = VoiceColors.Dark.Text.primary,
  surfaceVariant = VoiceColors.Dark.Surface.secondary,
  onSurfaceVariant = VoiceColors.Dark.Text.secondary,
  outline = VoiceColors.Dark.NeutralInverted.shade50,
  outlineVariant = VoiceColors.Dark.NeutralInverted.shade30,
  scrim = VoiceColors.Light.NeutralGray.black,
  inverseSurface = VoiceColors.Dark.Text.primary,
  inverseOnSurface = VoiceColors.Dark.Surface.main,
  inversePrimary = VoiceColors.Dark.PrimaryBlueBright.shade40,
  surfaceTint = VoiceColors.Dark.PrimaryBlueBright.shade60,
)
